{
  "id": "MAL-2024-5181",
  "modified": "2024-06-25T13:35:45Z",
  "published": "2024-06-25T13:35:45Z",
  "summary": "Malicious code in glovo-data-platform-declarative (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "glovo-data-platform-declarative",
        "purl": "pkg:pypi/glovo-data-platform-declarative"
      },
      "versions": [
        "999.9.19",
        "999.9.20",
        "999.9.18",
        "999.9.17"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/glovo-data-platform-declarative/MAL-2024-5181.json"
      }
    }
  ]
}